[project]
name = "criipto-signatures"
version = "0.1.0"
description = "A library for interacting with the Criipto signatures GraphQL API."
readme = "README.md"
authors = [
    { name = "Jan Aagaard Meier", email = "jan.meier@criipto.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gql[aiohttp]>=3.5.3",
    "pydantic>=2.11.7",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.7",
]
test = []

[tool.ruff]
indent-width = 2
