on: [push]
jobs:
  nodejs-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - name: Setup kernel for build, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
        working-directory: packages/nodejs
      - run: npm run check
        working-directory: packages/nodejs
      - run: npm run test:unit:nodejs

  dotnet-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet tool restore
      - run: dotnet csharpier --check .
        working-directory: packages/dotnet
      - run: npm run test:unit:dotnet
